2019-10-30 16:35:10,454 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1228, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-30 16:38:00,746 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1228, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

