2019-10-28 23:54:12,216 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-28 23:54:12,344 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-29 00:00:18,881 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-29 00:00:19,029 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-29 00:05:13,788 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1256, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-29 00:15:37,007 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1256, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-29 06:02:00,719 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1256, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-29 14:17:09,175 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1256, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-29 19:30:11,038 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-29 19:30:11,156 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-29 19:35:26,319 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1257, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-30 06:01:58,689 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1257, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-30 12:52:13,344 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1257, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

