2019-10-21 00:54:03,972 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-21 00:54:05,563 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-21 00:54:15,937 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-21 00:54:16,416 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-21 00:56:22,879 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-21 00:56:22,935 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-21 01:03:15,237 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-21 01:03:17,106 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-21 01:04:09,849 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-21 01:04:10,275 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-21 01:06:06,279 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-21 01:06:06,336 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-21 01:06:53,145 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-21 01:06:54,495 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-21 01:07:03,155 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-21 01:07:04,210 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-21 01:09:02,897 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-21 01:09:02,952 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-21 01:15:41,457 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-21 01:15:42,320 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-21 01:15:49,569 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-21 01:15:50,867 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-21 01:17:55,551 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-21 01:17:55,616 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-21 01:28:18,606 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-21 01:28:19,767 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-21 01:28:27,052 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-21 01:28:27,680 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-21 01:30:32,704 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-21 01:30:32,771 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-21 06:00:02,352 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-21 06:00:03,116 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-21 06:00:10,198 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-21 06:00:10,608 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-21 06:02:12,863 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-21 06:02:12,930 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-22 06:00:02,841 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 06:00:03,510 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 06:00:20,349 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 06:00:21,321 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 06:02:24,511 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-22 06:02:24,574 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-22 16:16:58,282 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 16:17:06,693 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 16:17:17,652 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 16:17:18,526 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 16:19:07,510 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "generate_data.py", line 1170, in <module>
    update_summarystats(sumstats, index_filepath)
  File "generate_data.py", line 216, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-22 16:22:01,583 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 16:22:03,896 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 16:22:15,436 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 16:22:16,234 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 16:24:07,806 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-22 16:24:07,859 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-22 16:36:45,899 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 16:36:46,766 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 16:36:56,290 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 16:36:56,662 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 16:38:44,462 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-22 16:38:44,515 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-22 17:16:37,617 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 17:16:41,368 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 17:16:54,284 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 17:16:55,221 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 17:18:37,904 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1172, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 218, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-22 17:27:42,371 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 17:27:43,336 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 17:27:52,807 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 17:27:55,503 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 17:29:57,519 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1172, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 218, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-22 17:35:29,288 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 17:35:31,416 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 17:35:40,785 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 17:35:41,539 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 17:37:43,698 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1172, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 218, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-22 17:40:50,471 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 17:40:51,639 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 17:41:05,991 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 17:41:08,328 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 17:41:21,581 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 17:41:22,521 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 17:43:25,000 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1172, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 218, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-22 17:44:03,747 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 17:44:07,709 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 17:44:25,323 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 17:44:26,156 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 17:46:29,579 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1172, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 218, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-22 18:55:23,897 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-22 18:55:26,226 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-22 18:56:02,742 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-22 18:56:03,559 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-22 18:57:46,079 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1254, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-23 06:00:03,332 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-23 06:00:04,049 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-23 06:00:12,336 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-23 06:00:12,735 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-23 06:02:15,508 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1254, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-24 06:00:02,871 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-24 06:00:04,310 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-24 06:00:28,458 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-24 06:00:29,092 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-24 06:02:31,657 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1254, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-25 06:00:14,813 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-25 06:00:19,713 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-25 06:00:52,070 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-25 06:00:52,465 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-25 06:02:54,963 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1254, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-26 06:00:04,778 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-26 06:00:06,979 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-26 06:00:16,289 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-26 06:00:16,689 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-26 06:02:18,619 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1254, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-26 23:35:32,438 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-26 23:35:33,472 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-26 23:35:41,842 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-26 23:35:42,344 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-26 23:35:44,727 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "generate_data.py", line 1240, in <module>
    make_bubbleplot_df(data_path)
  File "generate_data.py", line 1010, in make_bubbleplot_df
    'DISEASE/TRAIT', 'parentterm']].drop_duplicates()
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['DISEASE/TRAIT'] not in index"

2019-10-26 23:41:07,241 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-26 23:41:08,442 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-26 23:41:17,065 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-26 23:41:17,604 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-26 23:41:19,936 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "generate_data.py", line 1242, in <module>
    make_bubbleplot_df(data_path)
  File "generate_data.py", line 1014, in make_bubbleplot_df
    'DISEASE/TRAIT', 'parentterm']].drop_duplicates()
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['DISEASE/TRAIT'] not in index"

2019-10-26 23:42:37,327 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-26 23:42:38,810 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-26 23:42:46,834 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-26 23:42:47,340 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-26 23:42:50,073 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "generate_data.py", line 1242, in <module>
    make_bubbleplot_df(data_path)
  File "generate_data.py", line 1022, in make_bubbleplot_df
    'parentterm', 'DISEASE/TRAIT']],
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/tsl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['STUDY ACCESSION'] not in index"

2019-10-26 23:45:01,673 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-26 23:45:03,084 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-26 23:45:11,262 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-26 23:45:12,183 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-26 23:47:13,120 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-26 23:47:13,180 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-26 23:59:21,893 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-26 23:59:23,192 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-26 23:59:31,937 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-26 23:59:32,357 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 00:01:35,945 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-27 00:01:36,009 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-27 00:10:54,424 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 00:10:55,741 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 00:11:31,510 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-27 00:11:31,930 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 00:13:25,254 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-27 00:13:25,317 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-27 00:18:03,195 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 00:18:04,786 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 00:18:13,501 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-27 00:18:13,940 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 00:20:07,998 - diversity_logger - INFO - generate_data.py ran successfully!
2019-10-27 00:20:08,064 - diversity_logger - INFO - Successfully zipped the files to be downloaded
2019-10-27 00:25:37,429 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 00:25:38,644 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 00:25:46,945 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-27 00:25:47,366 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 00:27:46,444 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1258, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-27 06:00:02,509 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 06:00:03,221 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 06:00:10,286 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-27 06:00:10,721 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 06:02:06,831 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1258, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-27 10:25:48,100 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 10:25:49,024 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 10:25:56,591 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0-associations_e96_r2019-10-14.tsv
2019-10-27 10:25:57,203 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 10:27:45,784 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1258, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 300, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-27 10:49:33,961 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 10:49:34,942 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 10:49:42,821 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 10:51:30,871 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1260, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

2019-10-27 12:01:45,522 - diversity_logger - INFO - Successfully downloaded gwas_catalog_v1.0.2-studies_r2019-10-14.tsv
2019-10-27 12:01:46,289 - diversity_logger - INFO - Successfully downloaded gwas_catalog-ancestry_r2019-10-14.tsv
2019-10-27 12:02:03,035 - diversity_logger - INFO - Successfully downloaded efo-trait-mappings
2019-10-27 12:04:01,405 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: Traceback (most recent call last):
  File "gwasdiversitymonitor_app/generate_data.py", line 1260, in <module>
    update_summarystats(sumstats, index_filepath)
  File "gwasdiversitymonitor_app/generate_data.py", line 302, in update_summarystats
    with open(outpath, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsl/Dropbox/gwasdiversitymonitor/templates/sumstats.html'

